query GetInterestSolids($statuses: [String]) {
    Interest_Solids(
        limit: -1
        filter: { status: { _in: $statuses } }
        sort: ["sort"]
    ) {
        id
        Period
        Federal_and_Indian_Late_and_Underpayments
    }
}
