query GetPlantSpecificUCAs($statuses: [String]) {
  plant_specific_ucas(
    limit: -1
    filter: { status: { _in: $statuses } }
    sort: ["transportation_system_or_gas_plant"]
  ) {
    id
    transportation_system_or_gas_plant
    file {
      filename_download
      folder {
        name
      }
    }
    type
    operator
    location
    doc_date
  }
}
