version: 2.1

orbs:
  node: circleci/node@5.2.0

parameters:
  run-build-cms:
    type: boolean
    default: false

workflows:
  build-cms:
    when: << pipeline.parameters.run-build-cms >>
    jobs: 
      - install-node-deps:
          context:
            - org-global
      - node/run:
          app-dir: cms
          npm-run: build:all
          context:
            - org-global
      - deploy:
          requires: 
            - node/run
          context:
            - org-global

jobs:
  install-node-deps:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: '18.16.0'
      - node/install-packages:
          app-dir: cms
      - node/install-packages:
          app-dir: cms/src/extensions/endpoints/document
      - node/install-packages:
          app-dir: cms/src/extensions/endpoints/image-uploader
      - node/install-packages:
          app-dir: cms/src/extensions/endpoints/link-autocomplete
      - node/install-packages:
          app-dir: cms/src/extensions/endpoints/press-releases
      - node/install-packages:
          app-dir: cms/src/extensions/endpoints/reporter-letters
      - node/install-packages:
          app-dir: cms/src/extensions/endpoints/unbundling
      - node/install-packages:
          app-dir: cms/src/extensions/hooks/index-zones
      - node/install-packages:
          app-dir: cms/src/extensions/hooks/indian-gas-major-portion
      - node/install-packages:
          app-dir: cms/src/extensions/hooks/ibmp
      - node/install-packages:
          app-dir: cms/src/extensions/hooks/nymex
      - node/install-packages:
          app-dir: cms/src/extensions/interfaces/onrr-editor
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy to cloud.gov
          command: |
            chmod +x ./.circleci/scripts/deploy.sh
            ./.circleci/scripts/deploy.sh --branch "$CIRCLE_BRANCH" --manifest-path "cms"