version: 2.1

workflows:
  copy-database:
    jobs: 
      - database:
          context:
            - org-global
          filters:
            branches:
              only: main

jobs:
  database:
    docker: 
      - image: cimg/postgres:13.7
    steps:
      - checkout
      - run:
          name: Dump dev database
          command: |
            chmod +x ~/project/.circleci/scripts/dump-dev-db.sh
            ~/project/.circleci/scripts/dump-dev-db.sh
      - run:
          name: Load prod database from dev dump
          command: |
            chmod +x ~/project/.circleci/scripts/load-prod-db.sh
            ~/project/.circleci/scripts/load-prod-db.sh
      - store_artifacts:
          path: /tmp/onrr_database_backup.pg
          destination: onrr_database_backup.pg