version: 2.1

orbs:
  node: circleci/node@5.2.0

executors:
  frontend:
    resource_class: xlarge
    docker:
      - image: cimg/base:stable

parameters:
  run-build-frontend:
    type: boolean
    default: false
  run-copy-database:
    type: boolean
    default: false

workflows:
  build-frontend:
    when: << pipeline.parameters.run-build-frontend >>
    jobs: 
      - install-node-deps-frontend
      - build-frontend-app:
          context:
            - org-global
          requires:
            - install-node-deps-frontend
      - deploy-frontend:
          context:
            - org-global
          requires: 
            - build-frontend-app
  copy-database:
    when: << pipeline.parameters.run-copy-database >>
    jobs: 
      - database:
          context:
            - org-global

jobs:
  database:
    docker: 
      - image: cimg/postgres:13.7
    steps:
      - checkout
      - run:
          name: Dump dev database
          command: |
            ./scripts/dump-dev-db.sh
      - run:
          name: Load prod database from dev dump
          command: |
            ./scripts/load-prod-db.sh
      - store_artifacts:
          path: /tmp/onrr_database_backup.pg
          destination: onrr_database_backup.pg
  install-node-deps-frontend:
    executor: frontend
    steps:
      - checkout
      - node/install:
          node-version: '18.17.0'
      - node/install-packages:
          cache-path: ~/project/frontend/node_modules
          cache-version: v3
          app-dir: frontend
      - persist_to_workspace:
          root: ~/project
          paths: 
            - .
  build-frontend-app:
    resource_class: xlarge
    docker:
      - image: cimg/node:18.17.0
    working_directory: frontend
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Build frontend
          command: |
            npm run build:deploy
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./frontend/dist
  deploy-frontend:
    executor: frontend
    working_directory: frontend
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to cloud.gov
          command: |
            chmod +x ~/project/.circleci/scripts/deploy.sh
            ~/project/.circleci/scripts/deploy.sh --branch "$CIRCLE_BRANCH"