version: 2.1

orbs:
  node: circleci/node@5.2.0

executors:
  frontend:
    docker:
      - image: cimg/base:stable

parameters:
  run-build-frontend:
    type: boolean
    default: false
  run-copy-database:
    type: boolean
    default: false

workflows:
  build-frontend-frontend:
    when: << pipeline.parameters.run-build-frontend >>
    jobs: 
      - pre-build
      - node/run:
          app-dir: frontend
          npm-run: build:deploy
          context:
            - org-global
          requires:
            - pre-build-frontend
      - deploy-frontend:
          context:
            - org-global
          requires: 
            - node/run
  copy-database:
    when: << pipeline.parameters.run-copy-database >>
    jobs: 
      - database:
          context:
            - org-global

jobs:
  database:
    docker: 
      - image: cimg/postgres:13.7
    steps:
      - checkout
      - run:
          name: Dump dev database
          command: |
            ./scripts/dump-dev-db.sh
      - run:
          name: Load prod database from dev dump
          command: |
            ./scripts/load-prod-db.sh
      - store_artifacts:
          path: /tmp/onrr_database_backup.pg
          destination: onrr_database_backup.pg
  pre-build-frontend:
    working_directory: ~/onrr.gov-site/frontend
    executor: frontend
    steps:
      - checkout
      - node/install:
          node-version: '18.17.0'
      - node/install-packages:
          app-dir: frontend
  deploy-frontend:
    executor: frontend
    steps:
      - checkout
      - run:
          name: Deploy to cloud.gov
          command: |
            chmod +x ./.circleci/scripts/deploy.sh
            ./.circleci/scripts/deploy.sh --branch "$CIRCLE_BRANCH" --manifest-path "frontend"