fragment collectionBlockFields on collection_blocks {
  id
  collection
  header
  description
  accordion
  page
  tab
  items_per_page
  status
  layout
  item_status
  category_header_level
  topics
  __typename
}
