#import "./contentBlockFields.gql"
#import "./tabBlockFields.gql"
#import "./cardBlockFields.gql"
#import "./expansionPanelBlockFields.gql"
#import "./layoutColumnBlockFields.gql"
#import "./formulaBlockFields.gql"
#import "./collectionBlockFields.gql"

fragment pageFields on pages {
  id
  title
  slug
  hero_image {
    id
    description
  }
  hero_title
  page_blocks {
    id
    item {
      __typename
      ... on content_blocks {
        ...contentBlockFields
      }
      ... on tab_blocks {
        ...tabBlockFields
      }
      ... on card_blocks {
        ...cardBlockFields
      }
      ... on expansion_panels {
        ...expansionPanelBlockFields
      }
      ... on layout_column_blocks {
        ...layoutColumnBlockFields
      }
      ... on collection_blocks {
        ...collectionBlockFields
      }
    }
  }
  meta_title
  meta_description
}
