#import "./contentBlockFields.gql"
#import "./tabBlockFields.gql"
#import "./cardBlockFields.gql"
#import "./expansionPanelBlockFields.gql"
#import "./layoutColumnBlockFields.gql"
#import "./formulaBlockFields.gql"
#import "./collectionBlockFields.gql"
#import "./chartCardFields.gql"

fragment pageFields on pages {
  id
  title
  slug
  template
  topic_variant
  content_columns
  handbook {
    id
    title
    release
    download_url
    format
    intro
    note
    contact_group
    contact_name
    contact_email
    contact_phone
    chapters
    appendices
    guidance
    related
  }
  parent {
    title
    url
    parent {
      title
    }
  }
  hero_image {
    id
    description
  }
  hero_title
  hero_description
  hero_cta
  page_bands(sort: ["sort"]) {
    id
    heading
    body
    aside
    cta_label
    cta_url
    body_columns
    background
    card_variant
    chart {
      ...chartCardFields
    }
    steps(sort: ["sort"]) {
      id
      title
      body
    }
    cards(sort: ["sort"]) {
      id
      title
      body
      cta_label
      cta_url
    }
  }
  related_content
  journey_steps(sort: ["sort"]) {
    id
    label
    url
    body
    meta
  }
  journey_paths_heading
  journey_related_heading
  journey_references_heading
  journey_links(sort: ["sort"]) {
    id
    section
    variant
    title
    description
    link_label
    link_url
  }
  audience_heading
  services_heading
  data_heading
  audience_cards(sort: ["sort"]) {
    id
    title
    body
  }
  hub_services(sort: ["sort"]) {
    id
    title
    url
    description
  }
  hub_links(sort: ["sort"]) {
    id
    section
    title
    description
    link_label
    link_url
  }
  hub_chart {
    ...chartCardFields
  }
  dataset_metadata {
    id
    name
    description
    update_frequency
    formats
    coverage_start
    coverage_end
    publisher
    related_links
    about
    preview_component
    terms {
      glossary_terms_id {
        id
        term
        definition
      }
    }
    charts(sort: ["sort"]) {
      ...chartCardFields
    }
  }
  page_blocks {
    id
    item {
      __typename
      ... on content_blocks {
        ...contentBlockFields
      }
      ... on tab_blocks {
        ...tabBlockFields
      }
      ... on card_blocks {
        ...cardBlockFields
      }
      ... on expansion_panels {
        ...expansionPanelBlockFields
      }
      ... on layout_column_blocks {
        ...layoutColumnBlockFields
      }
      ... on collection_blocks {
        ...collectionBlockFields
      }
      ... on chart_cards {
        ...chartCardFields
      }
      ... on pay_gov_forms {
        id
        title
        description
        form_number
        pay_gov_url
      }
      ... on contact_boxes {
        id
        heading
        body
      }
      ... on data_tables {
        id
        source_collection
        source_field
        columns
        sort_field
        sort_direction
        # aliased: data_tables.filter (String) would otherwise collide with
        # chart_cards.filter (JSON) in the shared page_blocks.item selection.
        table_filter: filter
        row_limit
        caption
        show_caption
        compact
        as_of_label
        footnote
      }
    }
  }
  sidebar_blocks {
    id
    item {
      ... on content_blocks {
        ...contentBlockFields
        __typename
      }
      ... on collection_blocks {
        ...collectionBlockFields
        __typename
      }
    }
    __typename
  }
  meta_title
  meta_description
}
