query LandingPageProduction {
    production_totals: production_aggregated(
        groupBy: ["period", "commodity", "location"]
        filter: { _and: [
            {
                period: {
                    type: { _eq: "Monthly"}
                }
            },
            {
                commodity: {
                    product: { _in: ["Oil (bbl)", "Gas (mcf)", "Coal (tons)"] }
                }
            }
        ] }
        limit: -1
    ) {
        group
        sum {
            volume
        }
    }

    period(
        filter: { type: { _eq: "Monthly" } }
        sort: ["fiscal_year", "fiscal_month"]
        limit: -1
    ) {
        id
        fiscal_year
        fiscal_month
        month_short
        month_long
        calendar_year
        period_date
    }
    commodity(
        filter: { product: { _in: ["Oil (bbl)", "Gas (mcf)", "Coal (tons)"] } }
        limit: -1
    ) {
        id
        product
    }
    location(
        limit: -1
    ) {
        id
        source: land_type
    }
}
