query GetContactsByPage($page: String, $statuses: [String]) {
  contacts(
    sort: ["header", "letter"]
    limit: -1
    filter: {
      status: { _in: $statuses },
      page: { _eq: $page }
    }
  ) {
    id
    status
    page
    tab
    accordion
    company_yn
    letter
    header
    company_name
    operator_number
    agency
    people {
      id
      name
      role
      email
      phone
      is_primary
      fax
    }
  }
}
