services:
  database:
    container_name: database
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - directus_data:/var/lib/postgresql15/data
      - ./src:/src
      - ./ddl:/ddl
      - ./backup:/backup
      - ./static/csv:/static/csv
    networks:
      - directus
    env_file: ../../.env

networks:
  directus:

volumes:
  directus_data:
