version: '3.2'
services:
  database:
    container_name: database
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - directus_data:/var/lib/postgresql/data
      - ./src:/src
      - ./ddl:/ddl
      - ./backup:/backup
      - ./static/csv:/static/csv
  #   networks:
  #     - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

#   cache:
#     container_name: cache
#     image: redis:6
#     networks: 
#       - directus
#   directus:
#     container_name: directus
#     image: directus/directus:v9.0.0-rc.82
#     ports:
#       - 8055:8055
#     volumes:
#       # By default, Directus images writes uploads to /directus/uploads
#       # Always make sure your volumes matches the storage root when using
#       # local driver
#       - ./uploads:/directus/uploads
#       # Make sure to also mount the volume When using SQLite
#       # - ./database:/directus/database
#       # If you want to load extensions from the host
#       - ./extensions:/directus/extensions
#       - ./src:/directus/src
#       - ./dist:/directus/dist
#     networks:
#       - directus
#     depends_on:
#       - cache
#       - database
#     env_file: ../../.env

# networks:
#   directus:

volumes:
  directus_data:
