query GetMenuByLabel($menuLabel: String) {
    menus(filter: { 
      menu_label: { 
        _eq: $menuLabel 
      }
      menu: {
        _eq: "main"
      }
    }) {
        link_to_page {
            title
            url
        }
        menu_children {
            pages_id {
                title
                url
            }
        }
    }
}