query GetReporterLetters($statuses: [String]) {
  reporter_letters(
    limit: -1
    sort: ["-date"]
    filter: { status: { _in: $statuses } }
  ) {
    id
    title
    date
    file {
      id
      filename_download
      title
      type
    }
    accessible_file {
      id
      filename_download
      title
      type
    }
    link
    status
    topics
  }
}
