query GetRulemakings($statuses: [String]) {
  rulemakings(
    limit: -1
    filter: { status: { _in: $statuses }, rin: { _nnull: true } }
    sort: ["-rin"]
  ) {
    id
    final_publication_date
    rin
    rule_title
    commodity_subject_matter
    webpage_link
  }
}
