query GetProductionHandbook {
  production_handbook(
    limit: -1
    filter: { status: { _eq: "published" } }
    sort: ["sort"]
  ) {
    id
    chapter
    section
    title
    actual_page
    toc_page
    url
  }
}
