query GetProductionHandbook($statuses: [String]) {
  production_handbook(
    limit: -1
    filter: { status: { _in: $statuses } }
    sort: ["sort"]
  ) {
    id
    chapter
    section
    title
    actual_page
    toc_page
    url
  }
}
