#import "../../../fragments/eventFields.gql"

query GetEvents($statuses: [String]) {
  outreach_events: events(
    filter: {
      status: { _in: $statuses }
      event_end_date: { _gte: "$NOW" }
      is_training: { _eq: false }
    }
    sort: ["event_start_date"]
  ) {
    ...eventFields
  }
  other_events: events(
    filter: {
      status: { _in: $statuses }
      event_end_date: { _gte: "$NOW" }
      is_training: { _eq: true }
    }
    sort: ["event_start_date"]
  ) {
    ...eventFields
  }
}
